<a href="https://colab.research.google.com/github/amalmon/python-practice/blob/main/python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
sum = 10
for number in [2, 4, 6]:
    if number==6:
        sum = sum + number
    else:
        sum = 2
print(sum)

8


In [ ]:
x = 1
for i in range(5):
    x = x*i
print(x)

0


In [ ]:
print(x)

0


In [ ]:
for j in [0,1,2,3,4]: 
 a=j
print(a)


4


In [ ]:
for k in [0,1,2,3,4,5]: 
  print(k)


0
1
2
3
4
5


range(0, 5, 2)

In [ ]:
for l in range(0,5,1): print(l)


0
1
2
3
4


In [ ]:
for i in range(0,5): print(i)

0
1
2
3
4


In [ ]:
a='andi'
b='kindi'
a+b

'andikindi'

In [ ]:
import time;
ltime=time.localtime()
print(time.strftime("%a %b %d %H:%M:%S %z %Y",ltime))

Fri Jan 13 04:33:18 +0000 2023


In [ ]:
list=['p','r','o','b','l','e','m']
list.extend([1,2,3,'ku','khu','cha'])
list

['p', 'r', 'o', 'b', 'l', 'e', 'm', 1, 2, 3, 'ku', 'khu', 'cha']

In [ ]:
list

['p', 3, 'ku', 'khu', 'cha']

In [ ]:
del list[1:5]
list

['p', 'e', 'm', 1, 2, 3, 'ku', 'khu', 'cha']

In [ ]:
str(1462)[::-1]

'2641'

In [ ]:
n=5
for i in range(1,n+1):
 print(i)

1
2
3
4
5


In [ ]:
print(12,end="")

12

In [ ]:
a=1 2 3 4 5 6 7 8 9 
a.strip().split(' ')

SyntaxError: ignored

In [ ]:
import numpy
arr=numpy.array(input().split(),int)
arr.shape=(3,3)
print (arr)

KeyboardInterrupt: ignored

In [ ]:
arr=numpy.array('1 2 3 4'.split(),int)

In [ ]:
arr=numpy.array(input().split(),int)

1 2 3


In [ ]:
arr

array([1, 2, 3])

In [ ]:
1 2 3 4 5 6 7

In [ ]:
arr=numpy.array

In [ ]:
2 2
1 2
3 4

In [ ]:
import numpy
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(numpy.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr=numpy.array(input().split(),int)
print(arr)

11 22 23
[11 22 23]


In [ ]:
N, M =map(int, input().split()).tolist()

1 2 3 4 5 6 7


AttributeError: ignored

In [ ]:
import numpy
arry=list()
for _ in range(int(input().split()[0])):
    arry.append(list(map(int,input().split())))
print(numpy.array(arry).transpose(),numpy.array(arry).flatten(),sep="\n")

TypeError: ignored

In [ ]:
#1. User will input (3ages).Find the oldest one

In [ ]:


a=int(input())
b=int(input())
c=int(input())

list=[a,b,c]
print(max(list))

500
600
700
700


In [ ]:
a=int(input())
b=int(input())
c=int(input())

# we have a b c. frst compare a and b then compare the high number in a and b with c
# compare a & b eliminate smaller no. then compare big with c

max=a
if max<b:
  max=b
if max<c:
  max=c
print(max)

47
25
78
78


2.Write a program that will convert celsius value to fahrenheit

In [ ]:

x=float(input())
print((x*(9/5))+32)

37.778
100.0004


3.User will input (2numbers).Write a program to swap the numbers

In [ ]:
a=int(input('enter value of a '))
b=int(input('enter value of b '))
print('value of a',b)
print('value of b',a)

enter value of a 45
enter value of b 87
value of a 87
value of b 45


In [ ]:
a=int(input('enter value of a '))
b=int(input('enter value of b '))
temp=a #value of a stored to variable "temp"
a=b #then value of b assigned to a
b=temp  #then stored value of temp (ie value of a) assigned to b
print('value of a',a)
print('value of b',b)

enter value of a 78
enter value of b 54
value of a 54
value of b 78


4. Write a program that will give you the sum of 3 digits

In [ ]:
a=int(input())
b=int(input())
print(a+b)

111
222
333


In [ ]:
num=int(input())
x=num%10 # 456%10=6
num=num//10 # 456//10=45
y=num%10 # 45%10=5
num=num//10 # 45//10=4
z=num%10  # 4%10=4 (4/10=.4 reminder 4)
print(x+y+z)

456
15


5. Write a program that will reverse a four digit number.Also it checks whether the reverse is true.

In [ ]:
num=int(input())
r_num=0
while num/10!=0: 
    r_num=r_num*10
    r_num=r_num+num%10  
    num=num//10
print(r_num)


4567
7654


6. Write a program that will tell whether the number entered by the user is odd or even.

In [ ]:
a=int(input())
if a%2!=0:
  print('odd')
else:
  print('even')

49
odd


7. Write a program that will tell whether the given year is a leap year or not.

In [ ]:
y=int(input('year '))
if y%4!=0:
  print('not a leap yr')
else:
  print('leap yr')

year 2024
leap yr


8. Write a program to find the euclidean distance between two coordinates.


In [ ]:
x1=int(input('x1'))
y1=int(input('y1'))
x2=int(input('x2'))
y2=int(input('y2'))
d=((x2-x1)**2+(y2-y1)**2)**.5
print(d)

x11
y11
x25
y24
5.0


9. Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not.

In [7]:
angle_A=float(input())
angle_B=float(input())
angle_C=float(input())
if angle_A+angle_B+angle_C==180 and angle_A!=0 and angle_B!=0 and angle_C!=0:
  print('its a triangle')
else:
  print('not a triangle')

90
90
0
not a triangle


10. Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit.

In [17]:
a=int(input('cost price'))
b=int(input('sell price'))
if b-a>0:print ('porfit')
elif b-a==0:print('neither loss nor profit')
else:print('loss')

cost price100
sell price200
porfit


In [30]:
a=int(input('cost price'))
b=int(input('sell price'))
if b>a:
  amt=b-a
  print('prof=',amt)
elif a>b:
  amt=a-b
  print('loss=',amt)
else:print('neither loss nor profit')

cost price200
sell price200
neither loss nor profit


11. Write a program to find the simple interest when the value of principle,rate of interest and time period is given.

In [35]:
p=int(input('principle'))
i=int(input('roi'))
t=int(input('time period'))
si=(p*i*t)/100
a=p*(1+(i/100)*t)
print('simple_intrest=',si)
print('amount=',a)

principle100
roi10
time period2
simple_intrest= 20.0
amount= 120.0


12. Write a program to find the volume of the cylinder. Also find the cost when ,when the cost of 1litre milk is 40Rs.

13. Write  a program that will tell whether the given number is divisible by 3 & 6.

In [8]:
a=int(input())
if a%3==0 and a%6==0:
  print('no. divisible by 3 & 6')
else:print('not')

10
not


https://practice.geeksforgeeks.org/problems/angle-between-hour-and-minute-hand0545/1?page=2&category[]=Mathematical&category[]=Numbers&category[]=number-theory&sortBy=submissions

function to get angle between minute hand and hr. hand

In [ ]:
''' #get_angle(hr,mint.)
    angle(A) made by hr hand = hr*30+mint.*.5
    angle(B) made by mint. hand=mint.*6
    output:
    if A>B A-B degree
    if B>A B-A degree'''

In [35]:
def get_angle(h,m):
  "function gives the angle between hour and minute hands"
  x=range(1,13)
  y=range(0,60)
  if h not in x or m not in y:
    print("error")
  else:
    #angle made by hr hand from 12
    angle_a=h*30+m*.5
    #angle made by mint. hand from 12
    angle_b=m*6
    out_angle=angle_a-angle_b
    if -180<=out_angle<=180:
      print(abs(out_angle))
    else:
      print(360-abs(out_angle))

In [37]:
get_angle(12,1)

5.5


https://practice.geeksforgeeks.org/problems/overlapping-rectangles1924/1?page=3&category[]=Mathematical&category[]=Numbers&category[]=number-theory&sortBy=submissions

16. Write a program that will determine weather when the value of temperature and humidity is provided by the user.

TEMPERATURE(C). . . . . . . . . . . HUMIDITY(%). . . . . . . . .  WEATHER


      >= 30                             >=90                Hot and Humid

      >= 30                             < 90                 Hot

      <30                                >= 90               Cool and Humid

      <30                                 <90                 Cool

17. Write a program that will take three digits from the user and add the square of each digit.

18. Write a program that will check whether the number is armstrong number or not.

19. Write a program that will take user input of (4 digits number) and check whether the number is narcissist number or not.

20. Write a program that will give you the in hand salary after deduction of HRA(10%),DA(5%),PF(3%), and tax(if salary is between 5-10 lakh–10%),(11-20lakh–20%),(20< _   – 30%)(0-1lakh print k).